import type { Complaint, Profile } from '../types';

export const DEMO_GOVERNMENT_PROFILE: Profile = {
  id: 'demo-government-id',
  name: 'Demo Government Officer',
  email: 'demo.government@civicfix.local',
  phone: '+91 90000 12345',
  role: 'admin',
  department: 'Municipal Corporation',
  ward: 'Ward 42',
  created_at: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
};

export const DEMO_GOVERNMENT_COMPLAINTS: Complaint[] = [
  {
    id: 'CF-GOV-101',
    user_id: 'demo-citizen-id',
    category: 'pothole',
    description: 'Large pothole near MG Road is causing bicycle and scooter riders to swerve sharply during evening traffic.',
    photo_url: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
    resolution_photo_url: null,
    latitude: 12.9716,
    longitude: 77.5946,
    address: 'MG Road, Bengaluru, Karnataka',
    status: 'reported',
    demo_status_label: 'Pending',
    upvote_count: 28,
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    department: 'Public Works',
    assigned_officer_id: 'demo-government-id',
    assigned_officer: DEMO_GOVERNMENT_PROFILE,
    priority: 'high',
    sla_deadline: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    profile: DEMO_GOVERNMENT_PROFILE,
    has_upvoted: false,
  },
  {
    id: 'CF-GOV-102',
    user_id: 'demo-citizen-id',
    category: 'garbage',
    description: 'Overflowing community dustbins and dumped construction debris near the market entrance are attracting stray animals.',
    photo_url: 'https://images.unsplash.com/photo-1605600659873-d808a13e4d2a?auto=format&fit=crop&w=800&q=80',
    resolution_photo_url: null,
    latitude: 12.9352,
    longitude: 77.6245,
    address: 'Koramangala 7th Block Market Road, Bengaluru',
    status: 'in_progress',
    demo_status_label: 'In Progress',
    upvote_count: 18,
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    department: 'Sanitation',
    assigned_officer_id: 'demo-government-id',
    assigned_officer: DEMO_GOVERNMENT_PROFILE,
    priority: 'normal',
    sla_deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    profile: DEMO_GOVERNMENT_PROFILE,
    has_upvoted: true,
  },
  {
    id: 'CF-GOV-103',
    user_id: 'demo-citizen-id',
    category: 'streetlight',
    description: 'Three streetlights on the residential lane are not functioning after sunset, creating poor visibility and safety concerns.',
    photo_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
    resolution_photo_url: null,
    latitude: 12.9279,
    longitude: 77.6271,
    address: 'HSR Layout Sector 4, Bengaluru',
    status: 'resolved',
    demo_status_label: 'Resolved',
    upvote_count: 11,
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
    department: 'Electrical Services',
    assigned_officer_id: 'demo-government-id',
    assigned_officer: DEMO_GOVERNMENT_PROFILE,
    priority: 'low',
    sla_deadline: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    profile: DEMO_GOVERNMENT_PROFILE,
    has_upvoted: false,
  },
  {
    id: 'CF-GOV-104',
    user_id: 'demo-citizen-id',
    category: 'drainage',
    description: 'Sewage overflow from blocked drainage lines is pooling near the school gate and creating a foul smell after rain.',
    photo_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=800&q=80',
    resolution_photo_url: null,
    latitude: 12.9784,
    longitude: 77.6408,
    address: 'CMH Road near Metro Station, Indiranagar, Bengaluru',
    status: 'reported',
    demo_status_label: 'Overdue',
    upvote_count: 21,
    created_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    department: 'Drainage',
    assigned_officer_id: 'demo-government-id',
    assigned_officer: DEMO_GOVERNMENT_PROFILE,
    priority: 'critical',
    sla_deadline: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    profile: DEMO_GOVERNMENT_PROFILE,
    has_upvoted: false,
  },
  {
    id: 'CF-GOV-105',
    user_id: 'demo-citizen-id',
    category: 'water_supply',
    description: 'Low pressure and intermittent water supply is affecting households along the residential block after 7 PM every night.',
    photo_url: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80',
    resolution_photo_url: null,
    latitude: 12.9851,
    longitude: 77.5982,
    address: 'Vasanth Nagar, Bengaluru',
    status: 'in_progress',
    demo_status_label: 'In Progress',
    upvote_count: 15,
    created_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    department: 'Water Supply',
    assigned_officer_id: 'demo-government-id',
    assigned_officer: DEMO_GOVERNMENT_PROFILE,
    priority: 'high',
    sla_deadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    profile: DEMO_GOVERNMENT_PROFILE,
    has_upvoted: false,
  },
  {
    id: 'CF-GOV-106',
    user_id: 'demo-citizen-id',
    category: 'road_damage',
    description: 'Road damage and uneven surface on the service lane are worsening after each rain and creating repeated traffic hazards.',
    photo_url: 'https://images.unsplash.com/photo-1533558720647-e8c17d4a8d76?auto=format&fit=crop&w=800&q=80',
    resolution_photo_url: null,
    latitude: 12.9716,
    longitude: 77.5946,
    address: 'MG Road service lane, Bengaluru',
    status: 'reported',
    demo_status_label: 'Reopened',
    upvote_count: 33,
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    department: 'Public Works',
    assigned_officer_id: 'demo-government-id',
    assigned_officer: DEMO_GOVERNMENT_PROFILE,
    priority: 'critical',
    sla_deadline: new Date(Date.now() + 20 * 60 * 60 * 1000).toISOString(),
    profile: DEMO_GOVERNMENT_PROFILE,
    has_upvoted: true,
  },
  {
    id: 'CF-GOV-107',
    user_id: 'demo-citizen-id',
    category: 'pothole',
    description: 'Pothole repaired earlier but resurfaced near MG Road after the last monsoon week, with fresh cracking and water fill-up.',
    photo_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80',
    resolution_photo_url: null,
    latitude: 12.9717,
    longitude: 77.5949,
    address: 'MG Road near Metro Exit, Bengaluru',
    status: 'resolved',
    demo_status_label: 'Resolved',
    upvote_count: 13,
    created_at: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    department: 'Public Works',
    assigned_officer_id: 'demo-government-id',
    assigned_officer: DEMO_GOVERNMENT_PROFILE,
    priority: 'normal',
    sla_deadline: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    profile: DEMO_GOVERNMENT_PROFILE,
    has_upvoted: false,
  },
  {
    id: 'CF-GOV-108',
    user_id: 'demo-citizen-id',
    category: 'garbage',
    description: 'Waste collection delay in the civic lane is causing overflow at the municipal bin and foul smell near the bus stop.',
    photo_url: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80',
    resolution_photo_url: null,
    latitude: 12.9458,
    longitude: 77.6113,
    address: 'Bus Stop Lane, Domlur, Bengaluru',
    status: 'reported',
    demo_status_label: 'Pending',
    upvote_count: 9,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    department: 'Sanitation',
    assigned_officer_id: 'demo-government-id',
    assigned_officer: DEMO_GOVERNMENT_PROFILE,
    priority: 'low',
    sla_deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    profile: DEMO_GOVERNMENT_PROFILE,
    has_upvoted: false,
  },
];
